<a href="https://colab.research.google.com/github/JakeOh/202605_BD57/blob/main/lab_python/da02_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

# Series

*   한 가지 타입의 값 여러 개를 저장하는 1차원 모양의 데이터 타입(클래스)
*   축(axis) 레이블을 가지고 있는 1차원 배열.
    *   정수 기반의 인덱스와 축 레이블을 함께 갖고 있음.

In [2]:
s = pd.Series(data=[1, 2, -3, -4, 5])  # Series 클래스의 생성자 호출

In [3]:
print(s)

0    1
1    2
2   -3
3   -4
4    5
dtype: int64

In [4]:
s

0    1
1    2
2   -3
3   -4
4    5
dtype: int64

In [5]:
s.index  # Series 객체의 인덱스

RangeIndex(start=0, stop=5, step=1)

In [6]:
s.values  # Series 객체의 값들(numpy.ndarray)

array([ 1,  2, -3, -4,  5])

## indexing, slicing

*   `iloc`: numpy.ndarray에서 자동으로 부여되는 정수 인덱스를 기반으로 원소들을 참조.
    *   pandas.Series.values (ndarray 타입)가 가지고 있는 배열 인덱스를 사용.
    *   list 또는 ndarray에서 인덱스를 사용하는 방법과 같음.
    *   마지막 원소부터 거꾸로 부여되는 음수 인덱스를 사용할 수 있음.
*   `loc`: Series 객체를 생성할 때 설정하는 인덱스(레이블)를 기반으로 원소를 참조.
    *   ndarray(배열)의 인덱스와는 무관.
    *   마지막 원소부터 역순으로 자동 부여되는 음수 인덱스는 없음!

In [7]:
s.iloc[0]  # 시리즈에서 첫번째 원소

np.int64(1)

In [8]:
s.iloc[1]

np.int64(2)

In [9]:
s.iloc[-1]  # 시리즈에서 마지막 원소

np.int64(5)

In [10]:
s.iloc[1:3]  # slicing

1    2
2   -3
dtype: int64

In [12]:
s.iloc[:3]  # 시리즈에서 첫 3개 원소들을 잘라냄.

0    1
1    2
2   -3
dtype: int64

In [13]:
s.iloc[-3:]  # 시리즈에서 마지막 3개의 원소들을 잘라냄.

2   -3
3   -4
4    5
dtype: int64

In [14]:
s.loc[0]

np.int64(1)

In [15]:
s.loc[1]

np.int64(2)

In [16]:
s.loc[4]

np.int64(5)

In [ ]:
# s.loc[-1]  #> 에러 발생

In [18]:
s.loc[1:3]  #> iloc를 사용한 slicing과는 차이가 있음!

1    2
2   -3
3   -4
dtype: int64

In [19]:
s.loc[:3]

0    1
1    2
2   -3
3   -4
dtype: int64

In [20]:
s.loc[3:]

3   -4
4    5
dtype: int64

In [21]:
s.loc[-2:]

0    1
1    2
2   -3
3   -4
4    5
dtype: int64

In [22]:
s = pd.Series(data=[1, 2, -3, -4, 5],
              index=['a', 'b', 'x', 'y', 'z'])

In [23]:
s.index

Index(['a', 'b', 'x', 'y', 'z'], dtype='object')

In [24]:
s.values

array([ 1,  2, -3, -4,  5])

In [25]:
s

a    1
b    2
x   -3
y   -4
z    5
dtype: int64

In [26]:
s.iloc[0]  # iloc는 ndarray의 인덱스를 사용.

np.int64(1)

In [27]:
s.iloc[-1]

np.int64(5)

In [29]:
s.loc['a']

np.int64(1)

In [30]:
s.loc['a':'x']

a    1
b    2
x   -3
dtype: int64

In [31]:
s.loc[:'x']

a    1
b    2
x   -3
dtype: int64

In [33]:
s.loc['x':]  # s.loc['x':'z']

x   -3
y   -4
z    5
dtype: int64