<a href="https://colab.research.google.com/github/JakeOh/202605_BD57/blob/main/lab_python/da03_dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd  # Series, DataFrame
import seaborn as sns  # 시각화(그래프, 차트)

# 예제 데이터프레임

In [2]:
# seaborn 패키지에서 제공하는 tips.csv 파일을 읽어서 DataFrame을 생성
tips = sns.load_dataset('tips')

In [4]:
print(type(tips))

<class 'pandas.core.frame.DataFrame'>

In [5]:
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [6]:
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [7]:
tips.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [8]:
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

# 연습문제

*   숫자 타입 변수(컬럼)의 기술 통계량
*   카테고리 타입 변수의 빈도수
*   total_bill 컬럼의 값이 최댓값인 행을 출력
*   total_bill 컬럼의 값이 최솟값인 행을 출력
*   남성들의 tip의 평균
*   여성들의 tip의 평균
*   일요일의 tip의 평균
*   일요일 남성의 tip의 평균
*   일요일 여성의 tip의 평균

In [10]:
tips.describe()  # 숫자 타입 변수들의 기술 통계량

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [12]:
tips.sex.value_counts()  # 성별 빈도수

sex
Male      157
Female     87
Name: count, dtype: int64

In [15]:
tips['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [18]:
tips.smoker.value_counts()  # 흡연여부 빈도수

smoker
No     151
Yes     93
Name: count, dtype: int64

In [19]:
tips.day.value_counts()  # 요일 빈도수

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [22]:
tips.time.value_counts()  # (식사) 시간 빈도수

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [25]:
tips.size  #> DataFrame.size 속성: 행 개수 x 열 개수

1708

In [27]:
tips['size'].value_counts()  # 테이블 인원수 빈도수

size
2    156
3     38
4     37
5      5
1      4
6      4
Name: count, dtype: int64

In [29]:
# 영수증 금액 최댓값
tips.total_bill.max()

50.81

In [30]:
# 영수증 금액 최댓값인 행
tips[tips.total_bill == tips.total_bill.max()]

     total_bill   tip   sex smoker  day    time  size
170       50.81  10.0  Male    Yes  Sat  Dinner     3

In [31]:
# 영수증 금액 최솟값인 행
tips[tips.total_bill == tips.total_bill.min()]

    total_bill  tip     sex smoker  day    time  size
67        3.07  1.0  Female    Yes  Sat  Dinner     1

In [40]:
# 남성 팁의 평균
tips[tips.sex == 'Male'].tip.mean()

np.float64(3.0896178343949043)

In [48]:
tips.loc[tips.sex == 'Male', 'tip'].mean()

np.float64(3.0896178343949043)

In [52]:
# 여성 팁의 평균
tips[tips.sex == 'Female'].tip.mean()

np.float64(2.8334482758620685)

In [56]:
# 일요일 팁 평균
tips[tips.day == 'Sun'].tip.mean()

np.float64(3.2551315789473687)

In [59]:
# 일요일 남성 팁 평균
tips[(tips.day == 'Sun') & (tips.sex == 'Male')].tip.mean()

np.float64(3.2203448275862065)

In [60]:
# 일요일 여성 팁 평균
tips[(tips.day == 'Sun') & (tips.sex == 'Female')].tip.mean()

np.float64(3.3672222222222223)

In [74]:
tips['total_bill']  #> pandas.Series (1차원 데이터)

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [75]:
tips[['total_bill']]  #> pandas.DataFrame (2차원 데이터), 컬럼이 1개뿐인 데이터프레임.

     total_bill
0         16.99
1         10.34
2         21.01
3         23.68
4         24.59
..          ...
239       29.03
240       27.18
241       22.67
242       17.82
243       18.78

[244 rows x 1 columns]

# 파생 변수

기존의 컬럼 값들을 사용해서 새로운 컬럼을 추가하는 것.

In [76]:
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [78]:
# 영수증 금액 대비 팁의 비율
tips.tip / tips.total_bill

0      0.059447
1      0.160542
2      0.166587
3      0.139780
4      0.146808
         ...
239    0.203927
240    0.073584
241    0.088222
242    0.098204
243    0.159744
Length: 244, dtype: float64

In [79]:
# 파생 변수 추가: data_frame['new_col_name'] = 계산식
tips['tip_ratio'] = tips.tip / tips.total_bill

In [80]:
tips.head()

   total_bill   tip     sex smoker  day    time  size  tip_ratio
0       16.99  1.01  Female     No  Sun  Dinner     2   0.059447
1       10.34  1.66    Male     No  Sun  Dinner     3   0.160542
2       21.01  3.50    Male     No  Sun  Dinner     3   0.166587
3       23.68  3.31    Male     No  Sun  Dinner     2   0.139780
4       24.59  3.61  Female     No  Sun  Dinner     4   0.146808

*   팁/영수증 비율(tip_ratio)의 평균
*   팁/영수증 비율이 평균보다 큰 행들 출력
*   팁/영수증 비율이 평균보다 큰 데이터에서 남성/여성의 비율

In [82]:
tips.tip_ratio.mean()

np.float64(0.16080258172250472)

In [84]:
result = tips[tips.tip_ratio > tips.tip_ratio.mean()]

In [85]:
result

     total_bill   tip   sex smoker  day    time  size  tip_ratio
2         21.01  3.50  Male     No  Sun  Dinner     3   0.166587
5         25.29  4.71  Male     No  Sun  Dinner     4   0.186240
6          8.77  2.00  Male     No  Sun  Dinner     2   0.228050
9         14.78  3.23  Male     No  Sun  Dinner     2   0.218539
10        10.27  1.71  Male     No  Sun  Dinner     2   0.166504
..          ...   ...   ...    ...  ...     ...   ...        ...
228       13.28  2.72  Male     No  Sat  Dinner     2   0.204819
231       15.69  3.00  Male    Yes  Sat  Dinner     3   0.191205
232       11.61  3.39  Male     No  Sat  Dinner     2   0.291990
234       15.53  3.00  Male    Yes  Sat  Dinner     2   0.193175
239       29.03  5.92  Male     No  Sat  Dinner     3   0.203927

[107 rows x 8 columns]

In [87]:
result.sex.value_counts()

sex
Male      66
Female    41
Name: count, dtype: int64

In [88]:
result.sex.value_counts(normalize=True)

sex
Male      0.616822
Female    0.383178
Name: proportion, dtype: float64

In [90]:
# 전체 남성/여성 고객들 중에서 팁-영수증 비율이 평균보다 많은 남성/여성 고객 비율
result.sex.value_counts() / tips.sex.value_counts()

sex
Male      0.420382
Female    0.471264
Name: count, dtype: float64