<a href="https://colab.research.google.com/github/JakeOh/202605_BD57/blob/main/lab_python/da07_read.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

파일에서 DataFrame 생성하기

*   txt
*   csv(comma-separated values), tsv(tab-separated values)
*   xls, xlsx

In [1]:
import pandas as pd

# csv 파일의 첫번째 줄이 컬럼 이름인 경우

In [2]:
# github에 저장된 csv 파일 경로
ex1_path = 'https://raw.githubusercontent.com/wesm/pydata-book/refs/heads/3rd-edition/examples/ex1.csv'

In [3]:
ex1_df = pd.read_csv(ex1_path)

In [4]:
ex1_df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [5]:
ex1_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   a        3 non-null      int64
 1   b        3 non-null      int64
 2   c        3 non-null      int64
 3   d        3 non-null      int64
 4   message  3 non-null      object
dtypes: int64(4), object(1)
memory usage: 252.0+ bytes

# cvs 파일의 첫번째 줄부터 데이터인 경우(컬럼 이름이 없는 경우)

In [6]:
ex2_path = 'https://raw.githubusercontent.com/wesm/pydata-book/refs/heads/3rd-edition/examples/ex2.csv'

In [10]:
ex2_df = pd.read_csv(ex2_path,
                     names=['kor', 'eng', 'math', 'sci', 'msg'])

In [11]:
ex2_df

   kor  eng  math  sci    msg
0    1    2     3    4  hello
1    5    6     7    8  world
2    9   10    11   12    foo

In [12]:
ex2_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   kor     3 non-null      int64
 1   eng     3 non-null      int64
 2   math    3 non-null      int64
 3   sci     3 non-null      int64
 4   msg     3 non-null      object
dtypes: int64(4), object(1)
memory usage: 252.0+ bytes

`pandas.read_csv()` 함수의 names 파라미터는 DataFrame의 컬럼 레이블(이름)을 설정하기 위해서 사용.

*   csv 파일에 컬럼 레이블(이름)이 없는 경우. 파일의 첫번째 줄(행)부터 데이터인 경우.
*   csv 파일의 첫번째 행(줄)이 컬럼 이름인 경우에도, 컬럼 이름들을 원하는 이름으로 설정(재지정)하기 위해서 사용할 수도 있음.
    *   파일의 첫번째 줄(인덱스 0번 행)이 헤더임을 알려주기 위해서 `header=0` 파라미터와 함께 사용.

In [17]:
ex1_df = pd.read_csv(ex1_path,
                     names=['kor', 'eng', 'math', 'sci', 'msg'],
                     header=0)

In [18]:
ex1_df

   kor  eng  math  sci    msg
0    1    2     3    4  hello
1    5    6     7    8  world
2    9   10    11   12    foo

In [19]:
ex1_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   kor     3 non-null      int64
 1   eng     3 non-null      int64
 2   math    3 non-null      int64
 3   sci     3 non-null      int64
 4   msg     3 non-null      object
dtypes: int64(4), object(1)
memory usage: 252.0+ bytes

# 값들이 공백으로 구분된 텍스트 파일

In [20]:
ex3_path = 'https://raw.githubusercontent.com/wesm/pydata-book/refs/heads/3rd-edition/examples/ex3.txt'

In [24]:
ex3_df = pd.read_csv(ex3_path, sep='\\s+')  # sep와 delimiter는 같은 의미의 파라미터.

In [25]:
ex3_df  #> ex3.csv 파일은 행 인덱스들을 가지고 있었던 파일 -> DataFrame에서도 행 인덱스들이 만들어짐.

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

In [26]:
ex3_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, aaa to ddd
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       4 non-null      float64
 1   B       4 non-null      float64
 2   C       4 non-null      float64
dtypes: float64(3)
memory usage: 300.0+ bytes

# 컬럼 레이블과 데이터 이외의 주석 등을 포함하는 파일

In [27]:
ex4_path = 'https://raw.githubusercontent.com/wesm/pydata-book/refs/heads/3rd-edition/examples/ex4.csv'

In [28]:
ex4_df = pd.read_csv(ex4_path, skiprows=[0, 2, 3])

In [29]:
ex4_df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [30]:
ex4_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   a        3 non-null      int64
 1   b        3 non-null      int64
 2   c        3 non-null      int64
 3   d        3 non-null      int64
 4   message  3 non-null      object
dtypes: int64(4), object(1)
memory usage: 252.0+ bytes

*   csv(txt) 파일 --> DataFrame 생성: `pandas.read_csv()` 함수 사용.
*   DataFrame --> csv 파일 저장: `pandas.DataFrame.to_csv()` 메서드 사용.

In [31]:
# ex4_df 데이터프레임에 파생변수(새로운 컬럼)을 추가.
ex4_df['temp'] = 'TEST'
ex4_df

   a   b   c   d message  temp
0  1   2   3   4   hello  TEST
1  5   6   7   8   world  TEST
2  9  10  11  12     foo  TEST

In [32]:
ex4_df.to_csv('ex4.csv')  #> 행 인덱스(레이블)도 csv 파일에 write됨.

In [33]:
ex4_df.to_csv('ex4_noindex.csv', index=False)  # 행 인덱스는 파일에 write되지 않음.