<a href="https://colab.research.google.com/github/JakeOh/202605_BD57/blob/main/lab_python/da07_read.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

파일에서 DataFrame 생성하기

*   txt
*   csv(comma-separated values), tsv(tab-separated values)
*   xls, xlsx

In [1]:
import pandas as pd

# csv 파일의 첫번째 줄이 컬럼 이름인 경우

In [2]:
# github에 저장된 csv 파일 경로
ex1_path = 'https://raw.githubusercontent.com/wesm/pydata-book/refs/heads/3rd-edition/examples/ex1.csv'

In [3]:
ex1_df = pd.read_csv(ex1_path)

In [4]:
ex1_df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [5]:
ex1_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   a        3 non-null      int64
 1   b        3 non-null      int64
 2   c        3 non-null      int64
 3   d        3 non-null      int64
 4   message  3 non-null      object
dtypes: int64(4), object(1)
memory usage: 252.0+ bytes

# cvs 파일의 첫번째 줄부터 데이터인 경우(컬럼 이름이 없는 경우)

In [6]:
ex2_path = 'https://raw.githubusercontent.com/wesm/pydata-book/refs/heads/3rd-edition/examples/ex2.csv'

In [10]:
ex2_df = pd.read_csv(ex2_path,
                     names=['kor', 'eng', 'math', 'sci', 'msg'])

In [11]:
ex2_df

   kor  eng  math  sci    msg
0    1    2     3    4  hello
1    5    6     7    8  world
2    9   10    11   12    foo

In [12]:
ex2_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   kor     3 non-null      int64
 1   eng     3 non-null      int64
 2   math    3 non-null      int64
 3   sci     3 non-null      int64
 4   msg     3 non-null      object
dtypes: int64(4), object(1)
memory usage: 252.0+ bytes