<a href="https://colab.research.google.com/github/JakeOh/202605_BD57/blob/main/lab_python/da10_merge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 데이터프레임 합치기

*   merge: 두 개 이상의 데이터프레임을 공통된 컬럼(들)을 기준으로 합치는 것. SQL의 join과 비슷.
*   concat: 두 개 이상의 데이터프레임을 축(axis)을 따라서 합치는 것.

# Imports

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# merge

In [2]:
emp = pd.DataFrame(data={
    'empno': [101, 102, 201, 202],
    'ename': ['Scott', 'Allen', 'King', '오쌤'],
    'deptno': [10, 20, 10, 40],
})

In [3]:
emp

   empno  ename  deptno
0    101  Scott      10
1    102  Allen      20
2    201   King      10
3    202     오쌤      40

In [4]:
dept = pd.DataFrame(data={
    'deptno': [10, 20, 30],
    'dname': ['IT', 'HR', 'Sales'],
})

In [5]:
dept

   deptno  dname
0      10     IT
1      20     HR
2      30  Sales

*   `pandas.merge(left, right, how, on, ...)` 함수
*   `pandas.DataFrame.merge(right, how, on, ...)` 메서드
*   파라미터 `how`: merge 방식(inner, left, right, outer). 기본값은 inner.
*   파라미터 `on`: merge(join) 기준이 되는 컬럼(들의 리스트). merge하는 컬럼 이름이 같은 경우에는 생략 가능.

## inner join

In [6]:
pd.merge(left=emp, right=dept)

   empno  ename  deptno dname
0    101  Scott      10    IT
1    102  Allen      20    HR
2    201   King      10    IT

In [7]:
emp.merge(right=dept)

   empno  ename  deptno dname
0    101  Scott      10    IT
1    102  Allen      20    HR
2    201   King      10    IT

## left outer join

In [8]:
pd.merge(left=emp, right=dept, how='left')

   empno  ename  deptno dname
0    101  Scott      10    IT
1    102  Allen      20    HR
2    201   King      10    IT
3    202     오쌤      40   NaN

In [9]:
emp.merge(right=dept, how='left')

   empno  ename  deptno dname
0    101  Scott      10    IT
1    102  Allen      20    HR
2    201   King      10    IT
3    202     오쌤      40   NaN

## right outer join

In [10]:
pd.merge(left=emp, right=dept, how='right')

   empno  ename  deptno  dname
0  101.0  Scott      10     IT
1  201.0   King      10     IT
2  102.0  Allen      20     HR
3    NaN    NaN      30  Sales

In [11]:
emp.merge(right=dept, how='right')

   empno  ename  deptno  dname
0  101.0  Scott      10     IT
1  201.0   King      10     IT
2  102.0  Allen      20     HR
3    NaN    NaN      30  Sales

## full outer join

In [12]:
pd.merge(left=emp, right=dept, how='outer')

   empno  ename  deptno  dname
0  101.0  Scott      10     IT
1  201.0   King      10     IT
2  102.0  Allen      20     HR
3    NaN    NaN      30  Sales
4  202.0     오쌤      40    NaN

In [13]:
emp.merge(right=dept, how='outer')

   empno  ename  deptno  dname
0  101.0  Scott      10     IT
1  201.0   King      10     IT
2  102.0  Allen      20     HR
3    NaN    NaN      30  Sales
4  202.0     오쌤      40    NaN

## merge 기준 컬럼 이름이 다른 경우

In [14]:
dept2 = pd.DataFrame(data={
    'dept_id': [10, 20, 30],
    'dept_name': ['아이티', '인사', '영업']
})

In [15]:
dept2

   dept_id dept_name
0       10       아이티
1       20        인사
2       30        영업

In [16]:
# inner join
emp.merge(right=dept2, left_on='deptno', right_on='dept_id')

   empno  ename  deptno  dept_id dept_name
0    101  Scott      10       10       아이티
1    102  Allen      20       20        인사
2    201   King      10       10       아이티

In [17]:
# left outer join
emp.merge(right=dept2, how='left', left_on='deptno', right_on='dept_id')

   empno  ename  deptno  dept_id dept_name
0    101  Scott      10     10.0       아이티
1    102  Allen      20     20.0        인사
2    201   King      10     10.0       아이티
3    202     오쌤      40      NaN       NaN

In [18]:
# right outer join
emp.merge(right=dept2, how='right', left_on='deptno', right_on='dept_id')

   empno  ename  deptno  dept_id dept_name
0  101.0  Scott    10.0       10       아이티
1  201.0   King    10.0       10       아이티
2  102.0  Allen    20.0       20        인사
3    NaN    NaN     NaN       30        영업

In [19]:
# full outer join
emp.merge(right=dept2, how='outer', left_on='deptno', right_on='dept_id')

   empno  ename  deptno  dept_id dept_name
0  101.0  Scott    10.0     10.0       아이티
1  201.0   King    10.0     10.0       아이티
2  102.0  Allen    20.0     20.0        인사
3    NaN    NaN     NaN     30.0        영업
4  202.0     오쌤    40.0      NaN       NaN

## 인덱스(row label)로 merge

In [20]:
np.random.seed(42)

In [21]:
df1 = pd.DataFrame(data={'value1': np.random.randint(10, size=6),
                         'value2': np.random.randint(10, size=6),},
                   index=['a', 'b', 'c'] * 2)

In [22]:
df1

   value1  value2
a       6       2
b       3       6
c       7       7
a       4       4
b       6       3
c       9       7

In [23]:
df2 = pd.DataFrame(data={'data1': np.random.rand(3),
                         'data2': np.random.rand(3),},
                   index=['a', 'b', 'c'])

In [24]:
df2

      data1     data2
a  0.708073  0.832443
b  0.020584  0.212339
c  0.969910  0.181825

In [25]:
pd.merge(left=df1, right=df2, left_index=True, right_index=True)

   value1  value2     data1     data2
a       6       2  0.708073  0.832443
b       3       6  0.020584  0.212339
c       7       7  0.969910  0.181825
a       4       4  0.708073  0.832443
b       6       3  0.020584  0.212339
c       9       7  0.969910  0.181825

### 한쪽 데이터프레임은 컬럼으로, 다른 데이터프레임은 인덱스를 사용해서 merge

In [27]:
df3 = pd.DataFrame(data={
    'value1': np.random.randint(10, size=6),
    'value2': np.random.randint(100, size=6),
    'value3': ['a', 'b', 'c'] * 2
})

In [28]:
df3

   value1  value2 value3
0       9      50      a
1       2       6      b
2       6      20      c
3       3      72      a
4       8      38      b
5       2      17      c

In [29]:
df4 = pd.DataFrame(data={'data1': np.random.rand(3),
                         'data2': np.arange(10, 40, 10),},
                   index=['a', 'b', 'c'])

In [30]:
df4

      data1  data2
a  0.948886     10
b  0.965632     20
c  0.808397     30

In [31]:
pd.merge(left=df3, right=df4, left_on='value3', right_index=True)

   value1  value2 value3     data1  data2
0       9      50      a  0.948886     10
1       2       6      b  0.965632     20
2       6      20      c  0.808397     30
3       3      72      a  0.948886     10
4       8      38      b  0.965632     20
5       2      17      c  0.808397     30

# concat

## Series에서의 concat

In [32]:
s1 = pd.Series(data=['scott', 'tiger', 'king'])
s1

0    scott
1    tiger
2     king
dtype: object

In [33]:
s2 = pd.Series(data=['홍길동', '오쌤'])
s2

0    홍길동
1     오쌤
dtype: object

In [34]:
pd.concat([s1, s2])  #> s1과 s2의 인덱스가 유지.

0    scott
1    tiger
2     king
0      홍길동
1       오쌤
dtype: object

In [38]:
pd.concat([s1, s2], ignore_index=True)  #> s1과 s2의 인덱스들은 무시, RangeIndex가 새로 설정.

0    scott
1    tiger
2     king
3      홍길동
4       오쌤
dtype: object

In [37]:
s3 = pd.Series(data=['Sale', 'HR', 'IT'])
s3

0    Sale
1      HR
2      IT
dtype: object

In [41]:
pd.concat([s1, s3], axis=1)
# axis=0: 기본값. 행(row) 방향으로 이어붙이기.
# axis=1: 열(column) 방향으로 이어붙이기.

       0     1
0  scott  Sale
1  tiger    HR
2   king    IT

## DataFrame에서의 concat

In [42]:
np.random.seed(42)

In [43]:
score1 = pd.DataFrame(data={
    'id': np.arange(1, 6),
    'korean': np.random.randint(101, size=5),
    'english': np.random.randint(101, size=5),
    'math': np.random.randint(101, size=5),
})
score1

   id  korean  english  math
0   1      51       20    87
1   2      92       82    99
2   3      14       86    23
3   4      71       74     2
4   5      60       74    21

In [44]:
score2 = pd.DataFrame(data={
    'id': np.arange(6, 11),
    'korean': np.random.randint(101, size=5),
    'english': np.random.randint(101, size=5),
    'math': np.random.randint(101, size=5),
})
score2

   id  korean  english  math
0   6      52        1    75
1   7       1       63    57
2   8      87       59    21
3   9      29       20    88
4  10      37       32    48

In [46]:
pd.concat([score1, score2], ignore_index=True)

   id  korean  english  math
0   1      51       20    87
1   2      92       82    99
2   3      14       86    23
3   4      71       74     2
4   5      60       74    21
5   6      52        1    75
6   7       1       63    57
7   8      87       59    21
8   9      29       20    88
9  10      37       32    48

In [47]:
score3 = pd.DataFrame(data={
    'id': np.arange(1, 6),
    'science': np.random.randint(101, size=5),
    'history': np.random.randint(101, size=5),
    'art': np.random.randint(101, size=5),
})
score3

   id  science  history  art
0   1       90       79   61
1   2       58       14   50
2   3       41       61   54
3   4       91       61   63
4   5       59       46    2

In [48]:
pd.concat([score1, score3], axis=1)

   id  korean  english  math  id  science  history  art
0   1      51       20    87   1       90       79   61
1   2      92       82    99   2       58       14   50
2   3      14       86    23   3       41       61   54
3   4      71       74     2   4       91       61   63
4   5      60       74    21   5       59       46    2

In [49]:
pd.merge(left=score1, right=score3)

   id  korean  english  math  science  history  art
0   1      51       20    87       90       79   61
1   2      92       82    99       58       14   50
2   3      14       86    23       41       61   54
3   4      71       74     2       91       61   63
4   5      60       74    21       59       46    2

# merge, concat 연습 1

In [50]:
# CSV 파일 경로들
no2_file = 'https://github.com/pandas-dev/pandas/raw/refs/heads/main/doc/data/air_quality_no2_long.csv'
pm25_file = 'https://github.com/pandas-dev/pandas/raw/refs/heads/main/doc/data/air_quality_pm25_long.csv'
stations_file = 'https://github.com/pandas-dev/pandas/raw/refs/heads/main/doc/data/air_quality_stations.csv'

미세먼지 농도 데이터셋

*   위의 3개 csv 파일을 읽고, 각각 데이터프레임을 생성.
*   no2_df, pm25_df 데이터프레임을 합치세요.(merge? concat?)
*   위에 합쳐진 데이터프레임과 stations_df 데이터프레임을 합치세요.(merge? concat?)
*   데이터프레임 탐색.