<a href="https://colab.research.google.com/github/JakeOh/202605_BD57/blob/main/lab_python/da10_merge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 데이터프레임 합치기

*   merge: 두 개 이상의 데이터프레임을 공통된 컬럼(들)을 기준으로 합치는 것. SQL의 join과 비슷.
*   concat: 두 개 이상의 데이터프레임을 축(axis)을 따라서 합치는 것.

# Imports

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# merge

In [2]:
emp = pd.DataFrame(data={
    'empno': [101, 102, 201, 202],
    'ename': ['Scott', 'Allen', 'King', '오쌤'],
    'deptno': [10, 20, 10, 40],
})

In [3]:
emp

   empno  ename  deptno
0    101  Scott      10
1    102  Allen      20
2    201   King      10
3    202     오쌤      40

In [4]:
dept = pd.DataFrame(data={
    'deptno': [10, 20, 30],
    'dname': ['IT', 'HR', 'Sales'],
})

In [5]:
dept

   deptno  dname
0      10     IT
1      20     HR
2      30  Sales

*   `pandas.merge(left, right, how, on, ...)` 함수
*   `pandas.DataFrame.merge(right, how, on, ...)` 메서드
*   파라미터 `how`: merge 방식(inner, left, right, outer). 기본값은 inner.
*   파라미터 `on`: merge(join) 기준이 되는 컬럼(들의 리스트). merge하는 컬럼 이름이 같은 경우에는 생략 가능.

## inner join

In [6]:
pd.merge(left=emp, right=dept)

   empno  ename  deptno dname
0    101  Scott      10    IT
1    102  Allen      20    HR
2    201   King      10    IT

In [7]:
emp.merge(right=dept)

   empno  ename  deptno dname
0    101  Scott      10    IT
1    102  Allen      20    HR
2    201   King      10    IT

## left outer join

In [8]:
pd.merge(left=emp, right=dept, how='left')

   empno  ename  deptno dname
0    101  Scott      10    IT
1    102  Allen      20    HR
2    201   King      10    IT
3    202     오쌤      40   NaN

In [9]:
emp.merge(right=dept, how='left')

   empno  ename  deptno dname
0    101  Scott      10    IT
1    102  Allen      20    HR
2    201   King      10    IT
3    202     오쌤      40   NaN

## right outer join

In [10]:
pd.merge(left=emp, right=dept, how='right')

   empno  ename  deptno  dname
0  101.0  Scott      10     IT
1  201.0   King      10     IT
2  102.0  Allen      20     HR
3    NaN    NaN      30  Sales

In [11]:
emp.merge(right=dept, how='right')

   empno  ename  deptno  dname
0  101.0  Scott      10     IT
1  201.0   King      10     IT
2  102.0  Allen      20     HR
3    NaN    NaN      30  Sales

## full outer join

In [12]:
pd.merge(left=emp, right=dept, how='outer')

   empno  ename  deptno  dname
0  101.0  Scott      10     IT
1  201.0   King      10     IT
2  102.0  Allen      20     HR
3    NaN    NaN      30  Sales
4  202.0     오쌤      40    NaN

In [13]:
emp.merge(right=dept, how='outer')

   empno  ename  deptno  dname
0  101.0  Scott      10     IT
1  201.0   King      10     IT
2  102.0  Allen      20     HR
3    NaN    NaN      30  Sales
4  202.0     오쌤      40    NaN

## merge 기준 컬럼 이름이 다른 경우

In [14]:
dept2 = pd.DataFrame(data={
    'dept_id': [10, 20, 30],
    'dept_name': ['아이티', '인사', '영업']
})

In [15]:
dept2

   dept_id dept_name
0       10       아이티
1       20        인사
2       30        영업

In [16]:
# inner join
emp.merge(right=dept2, left_on='deptno', right_on='dept_id')

   empno  ename  deptno  dept_id dept_name
0    101  Scott      10       10       아이티
1    102  Allen      20       20        인사
2    201   King      10       10       아이티

In [17]:
# left outer join
emp.merge(right=dept2, how='left', left_on='deptno', right_on='dept_id')

   empno  ename  deptno  dept_id dept_name
0    101  Scott      10     10.0       아이티
1    102  Allen      20     20.0        인사
2    201   King      10     10.0       아이티
3    202     오쌤      40      NaN       NaN

In [18]:
# right outer join
emp.merge(right=dept2, how='right', left_on='deptno', right_on='dept_id')

   empno  ename  deptno  dept_id dept_name
0  101.0  Scott    10.0       10       아이티
1  201.0   King    10.0       10       아이티
2  102.0  Allen    20.0       20        인사
3    NaN    NaN     NaN       30        영업

In [19]:
# full outer join
emp.merge(right=dept2, how='outer', left_on='deptno', right_on='dept_id')

   empno  ename  deptno  dept_id dept_name
0  101.0  Scott    10.0     10.0       아이티
1  201.0   King    10.0     10.0       아이티
2  102.0  Allen    20.0     20.0        인사
3    NaN    NaN     NaN     30.0        영업
4  202.0     오쌤    40.0      NaN       NaN

## 인덱스(row label)로 merge

In [20]:
np.random.seed(42)

In [21]:
df1 = pd.DataFrame(data={'value1': np.random.randint(10, size=6),
                         'value2': np.random.randint(10, size=6),},
                   index=['a', 'b', 'c'] * 2)

In [22]:
df1

   value1  value2
a       6       2
b       3       6
c       7       7
a       4       4
b       6       3
c       9       7

In [23]:
df2 = pd.DataFrame(data={'data1': np.random.rand(3),
                         'data2': np.random.rand(3),},
                   index=['a', 'b', 'c'])

In [24]:
df2

      data1     data2
a  0.708073  0.832443
b  0.020584  0.212339
c  0.969910  0.181825

In [25]:
pd.merge(left=df1, right=df2, left_index=True, right_index=True)

   value1  value2     data1     data2
a       6       2  0.708073  0.832443
b       3       6  0.020584  0.212339
c       7       7  0.969910  0.181825
a       4       4  0.708073  0.832443
b       6       3  0.020584  0.212339
c       9       7  0.969910  0.181825

### 한쪽 데이터프레임은 컬럼으로, 다른 데이터프레임은 인덱스를 사용해서 merge

In [27]:
df3 = pd.DataFrame(data={
    'value1': np.random.randint(10, size=6),
    'value2': np.random.randint(100, size=6),
    'value3': ['a', 'b', 'c'] * 2
})

In [28]:
df3

   value1  value2 value3
0       9      50      a
1       2       6      b
2       6      20      c
3       3      72      a
4       8      38      b
5       2      17      c

In [29]:
df4 = pd.DataFrame(data={'data1': np.random.rand(3),
                         'data2': np.arange(10, 40, 10),},
                   index=['a', 'b', 'c'])

In [30]:
df4

      data1  data2
a  0.948886     10
b  0.965632     20
c  0.808397     30

In [31]:
pd.merge(left=df3, right=df4, left_on='value3', right_index=True)

   value1  value2 value3     data1  data2
0       9      50      a  0.948886     10
1       2       6      b  0.965632     20
2       6      20      c  0.808397     30
3       3      72      a  0.948886     10
4       8      38      b  0.965632     20
5       2      17      c  0.808397     30

# concat

## Series에서의 concat

In [32]:
s1 = pd.Series(data=['scott', 'tiger', 'king'])
s1

0    scott
1    tiger
2     king
dtype: object

In [33]:
s2 = pd.Series(data=['홍길동', '오쌤'])
s2

0    홍길동
1     오쌤
dtype: object

In [34]:
pd.concat([s1, s2])  #> s1과 s2의 인덱스가 유지.

0    scott
1    tiger
2     king
0      홍길동
1       오쌤
dtype: object

In [38]:
pd.concat([s1, s2], ignore_index=True)  #> s1과 s2의 인덱스들은 무시, RangeIndex가 새로 설정.

0    scott
1    tiger
2     king
3      홍길동
4       오쌤
dtype: object

In [37]:
s3 = pd.Series(data=['Sale', 'HR', 'IT'])
s3

0    Sale
1      HR
2      IT
dtype: object

In [41]:
pd.concat([s1, s3], axis=1)
# axis=0: 기본값. 행(row) 방향으로 이어붙이기.
# axis=1: 열(column) 방향으로 이어붙이기.

       0     1
0  scott  Sale
1  tiger    HR
2   king    IT

## DataFrame에서의 concat

In [42]:
np.random.seed(42)

In [43]:
score1 = pd.DataFrame(data={
    'id': np.arange(1, 6),
    'korean': np.random.randint(101, size=5),
    'english': np.random.randint(101, size=5),
    'math': np.random.randint(101, size=5),
})
score1

   id  korean  english  math
0   1      51       20    87
1   2      92       82    99
2   3      14       86    23
3   4      71       74     2
4   5      60       74    21

In [44]:
score2 = pd.DataFrame(data={
    'id': np.arange(6, 11),
    'korean': np.random.randint(101, size=5),
    'english': np.random.randint(101, size=5),
    'math': np.random.randint(101, size=5),
})
score2

   id  korean  english  math
0   6      52        1    75
1   7       1       63    57
2   8      87       59    21
3   9      29       20    88
4  10      37       32    48

In [46]:
pd.concat([score1, score2], ignore_index=True)

   id  korean  english  math
0   1      51       20    87
1   2      92       82    99
2   3      14       86    23
3   4      71       74     2
4   5      60       74    21
5   6      52        1    75
6   7       1       63    57
7   8      87       59    21
8   9      29       20    88
9  10      37       32    48

In [47]:
score3 = pd.DataFrame(data={
    'id': np.arange(1, 6),
    'science': np.random.randint(101, size=5),
    'history': np.random.randint(101, size=5),
    'art': np.random.randint(101, size=5),
})
score3

   id  science  history  art
0   1       90       79   61
1   2       58       14   50
2   3       41       61   54
3   4       91       61   63
4   5       59       46    2

In [48]:
pd.concat([score1, score3], axis=1)

   id  korean  english  math  id  science  history  art
0   1      51       20    87   1       90       79   61
1   2      92       82    99   2       58       14   50
2   3      14       86    23   3       41       61   54
3   4      71       74     2   4       91       61   63
4   5      60       74    21   5       59       46    2

In [49]:
pd.merge(left=score1, right=score3)

   id  korean  english  math  science  history  art
0   1      51       20    87       90       79   61
1   2      92       82    99       58       14   50
2   3      14       86    23       41       61   54
3   4      71       74     2       91       61   63
4   5      60       74    21       59       46    2

# merge, concat 연습 1

In [50]:
# CSV 파일 경로들
no2_file = 'https://github.com/pandas-dev/pandas/raw/refs/heads/main/doc/data/air_quality_no2_long.csv'
pm25_file = 'https://github.com/pandas-dev/pandas/raw/refs/heads/main/doc/data/air_quality_pm25_long.csv'
stations_file = 'https://github.com/pandas-dev/pandas/raw/refs/heads/main/doc/data/air_quality_stations.csv'

미세먼지 농도 데이터셋

*   위 3개의 csv 파일을 읽고, 각각 데이터프레임을 생성.
*   no2_df, pm25_df 데이터프레임을 합치세요.(merge? concat?)
*   위에서 합쳐진 데이터프레임과 stations_df 데이터프레임을 합치세요.(merge? concat?)
*   데이터프레임 탐색.

## no2 데이터셋

In [51]:
no2_df = pd.read_csv(no2_file)

In [52]:
no2_df.head()

    city country                   date.utc location parameter  value   unit
0  Paris      FR  2019-06-21 00:00:00+00:00  FR04014       no2   20.0  µg/m³
1  Paris      FR  2019-06-20 23:00:00+00:00  FR04014       no2   21.8  µg/m³
2  Paris      FR  2019-06-20 22:00:00+00:00  FR04014       no2   26.5  µg/m³
3  Paris      FR  2019-06-20 21:00:00+00:00  FR04014       no2   24.9  µg/m³
4  Paris      FR  2019-06-20 20:00:00+00:00  FR04014       no2   21.4  µg/m³

In [53]:
no2_df.tail()

,city,country,date.utc,location,parameter,value,unit
2063,London,GB,2019-05-07 06:00:00+00:00,London Westminster,no2,26.0,µg/m³
2064,London,GB,2019-05-07 04:00:00+00:00,London Westminster,no2,16.0,µg/m³
2065,London,GB,2019-05-07 03:00:00+00:00,London Westminster,no2,19.0,µg/m³
2066,London,GB,2019-05-07 02:00:00+00:00,London Westminster,no2,19.0,µg/m³
2067,London,GB,2019-05-07 01:00:00+00:00,London Westminster,no2,23.0,µg/m³

In [54]:
no2_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2068 entries, 0 to 2067
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   city       2068 non-null   object
 1   country    2068 non-null   object
 2   date.utc   2068 non-null   object
 3   location   2068 non-null   object
 4   parameter  2068 non-null   object
 5   value      2068 non-null   float64
 6   unit       2068 non-null   object
dtypes: float64(1), object(6)
memory usage: 113.2+ KB

In [55]:
no2_df.city.unique()

array(['Paris', 'Antwerpen', 'London'], dtype=object)

In [56]:
no2_df.country.unique()

array(['FR', 'BE', 'GB'], dtype=object)

In [57]:
no2_df.location.unique()

array(['FR04014', 'BETR801', 'London Westminster'], dtype=object)

In [58]:
no2_df.parameter.unique()

array(['no2'], dtype=object)

In [59]:
no2_df.unit.unique()

array(['µg/m³'], dtype=object)

In [61]:
no2_df.value.describe()

count    2068.000000
mean       26.261847
std        13.479451
min         0.000000
25%        17.000000
50%        25.000000
75%        33.000000
max        97.000000
Name: value, dtype: float64

In [62]:
no2_df.city.value_counts()

city
Paris        1004
London        969
Antwerpen      95
Name: count, dtype: int64

In [63]:
no2_df.country.value_counts()

country
FR    1004
GB     969
BE      95
Name: count, dtype: int64

In [64]:
no2_df.location.value_counts()

location
FR04014               1004
London Westminster     969
BETR801                 95
Name: count, dtype: int64

## pm25 데이터셋

In [65]:
pm25_df = pd.read_csv(pm25_file)

In [66]:
pm25_df.head()

,city,country,date.utc,location,parameter,value,unit
0,Antwerpen,BE,2019-06-18 06:00:00+00:00,BETR801,pm25,18.0,µg/m³
1,Antwerpen,BE,2019-06-17 08:00:00+00:00,BETR801,pm25,6.5,µg/m³
2,Antwerpen,BE,2019-06-17 07:00:00+00:00,BETR801,pm25,18.5,µg/m³
3,Antwerpen,BE,2019-06-17 06:00:00+00:00,BETR801,pm25,16.0,µg/m³
4,Antwerpen,BE,2019-06-17 05:00:00+00:00,BETR801,pm25,7.5,µg/m³

In [67]:
pm25_df.tail()

,city,country,date.utc,location,parameter,value,unit
1105,London,GB,2019-05-07 06:00:00+00:00,London Westminster,pm25,9.0,µg/m³
1106,London,GB,2019-05-07 04:00:00+00:00,London Westminster,pm25,8.0,µg/m³
1107,London,GB,2019-05-07 03:00:00+00:00,London Westminster,pm25,8.0,µg/m³
1108,London,GB,2019-05-07 02:00:00+00:00,London Westminster,pm25,8.0,µg/m³
1109,London,GB,2019-05-07 01:00:00+00:00,London Westminster,pm25,8.0,µg/m³

In [68]:
pm25_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1110 entries, 0 to 1109
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   city       1110 non-null   object
 1   country    1110 non-null   object
 2   date.utc   1110 non-null   object
 3   location   1110 non-null   object
 4   parameter  1110 non-null   object
 5   value      1110 non-null   float64
 6   unit       1110 non-null   object
dtypes: float64(1), object(6)
memory usage: 60.8+ KB

In [69]:
pm25_df.city.unique()

array(['Antwerpen', 'London'], dtype=object)

In [70]:
pm25_df.city.value_counts()

city
London       1009
Antwerpen     101
Name: count, dtype: int64

In [71]:
pm25_df.country.unique()

array(['BE', 'GB'], dtype=object)

In [72]:
pm25_df.country.value_counts()

country
GB    1009
BE     101
Name: count, dtype: int64

In [73]:
pm25_df.parameter.unique()

array(['pm25'], dtype=object)

In [74]:
pm25_df.value.describe()

count    1110.000000
mean       10.131532
std         6.703820
min         3.000000
25%         7.000000
50%         8.000000
75%        11.000000
max        60.000000
Name: value, dtype: float64

## stations 데이터셋

In [75]:
stations_df = pd.read_csv(stations_file)

In [76]:
stations_df.head()

  location  coordinates.latitude  coordinates.longitude
0  BELAL01              51.23619                4.38522
1  BELHB23              51.17030                4.34100
2  BELLD01              51.10998                5.00486
3  BELLD02              51.12038                5.02155
4  BELR833              51.32766                4.36226

In [77]:
stations_df.tail()

                      location  coordinates.latitude  coordinates.longitude
61             Southend-on-Sea              51.54420                0.67841
62  Southwark A2 Old Kent Road              51.48050               -0.05955
63                    Thurrock              51.47707                0.31797
64      Tower Hamlets Roadside              51.52253               -0.04216
65        Groton Fort Griswold              41.35360              -72.07890

In [78]:
stations_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 3 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   location               66 non-null     object
 1   coordinates.latitude   66 non-null     float64
 2   coordinates.longitude  66 non-null     float64
dtypes: float64(2), object(1)
memory usage: 1.7+ KB

In [79]:
stations_df.location.unique()

array(['BELAL01', 'BELHB23', 'BELLD01', 'BELLD02', 'BELR833', 'BELSA04',
       'BELWZ02', 'BETM802', 'BETN016', 'BETR801', 'BETR802', 'BETR803',
       'BETR805', 'BETR811', 'BETR815', 'BETR817', 'BETR820', 'BETR822',
       'BETR831', 'BETR834', 'BETR891', 'BETR893', 'BETR894', 'BETR897',
       'FR04004', 'FR04012', 'FR04014', 'FR04031', 'FR04037', 'FR04060',
       'FR04071', 'FR04118', 'FR04131', 'FR04135', 'FR04141', 'FR04143',
       'FR04179', 'FR04329', 'Camden Kerbside', 'Ealing Horn Lane',
       'Haringey Roadside', 'London Bexley', 'London Bloomsbury',
       'London Eltham', 'London Haringey Priory Park South',
       'London Harlington', 'London Harrow Stanmore', 'London Hillingdon',
       'London Marylebone Road', 'London N. Kensington',
       'London Teddington', 'London Teddington Bushy Park',
       'London Westminster', 'Southend-on-Sea',
       'Southwark A2 Old Kent Road', 'Thurrock', 'Tower Hamlets Roadside',
       'Groton Fort Griswold'], dtype=object)

In [80]:
len(stations_df.location.unique())

58

In [81]:
stations_df.location.value_counts()

location
FR04031                              2
FR04014                              2
FR04141                              2
FR04143                              2
FR04329                              2
FR04135                              2
FR04071                              2
FR04118                              2
BELAL01                              1
BELHB23                              1
BETR802                              1
BETR803                              1
BETR805                              1
BETR811                              1
BETR815                              1
BETR817                              1
BETR820                              1
BETR822                              1
BELLD01                              1
BELLD02                              1
BELR833                              1
BELSA04                              1
BELWZ02                              1
BETM802                              1
BETN016                              1
BETR801                              1
FR04012                              1
FR04004                              1
BETR897                              1
BETR894                              1
BETR893                              1
BETR891                              1
BETR834                              1
BETR831                              1
FR04131                              1
FR04060                              1
FR04037                              1
FR04179                              1
Camden Kerbside                      1
Ealing Horn Lane                     1
Haringey Roadside                    1
London Bexley                        1
London Bloomsbury                    1
London Eltham                        1
London Haringey Priory Park South    1
London Harlington                    1
London Harrow Stanmore               1
London Hillingdon                    1
London Marylebone Road               1
London N. Kensington                 1
London Teddington                    1
London Teddington Bushy Park         1
London Westminster                   1
Southend-on-Sea                      1
Southwark A2 Old Kent Road           1
Thurrock                             1
Tower Hamlets Roadside               1
Groton Fort Griswold                 1
Name: count, dtype: int64

In [82]:
stations_df[stations_df.location == 'FR04031']

   location  coordinates.latitude  coordinates.longitude
28  FR04031              48.86887                2.31194
29  FR04031              48.86889                2.31194

## no2와 pm25 데이터프레임 합치기(concat)

In [83]:
air_quality = pd.concat([no2_df, pm25_df], ignore_index=True)

In [84]:
air_quality.head()

    city country                   date.utc location parameter  value   unit
0  Paris      FR  2019-06-21 00:00:00+00:00  FR04014       no2   20.0  µg/m³
1  Paris      FR  2019-06-20 23:00:00+00:00  FR04014       no2   21.8  µg/m³
2  Paris      FR  2019-06-20 22:00:00+00:00  FR04014       no2   26.5  µg/m³
3  Paris      FR  2019-06-20 21:00:00+00:00  FR04014       no2   24.9  µg/m³
4  Paris      FR  2019-06-20 20:00:00+00:00  FR04014       no2   21.4  µg/m³

In [85]:
air_quality.tail()

,city,country,date.utc,location,parameter,value,unit
3173,London,GB,2019-05-07 06:00:00+00:00,London Westminster,pm25,9.0,µg/m³
3174,London,GB,2019-05-07 04:00:00+00:00,London Westminster,pm25,8.0,µg/m³
3175,London,GB,2019-05-07 03:00:00+00:00,London Westminster,pm25,8.0,µg/m³
3176,London,GB,2019-05-07 02:00:00+00:00,London Westminster,pm25,8.0,µg/m³
3177,London,GB,2019-05-07 01:00:00+00:00,London Westminster,pm25,8.0,µg/m³

In [86]:
air_quality.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3178 entries, 0 to 3177
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   city       3178 non-null   object
 1   country    3178 non-null   object
 2   date.utc   3178 non-null   object
 3   location   3178 non-null   object
 4   parameter  3178 non-null   object
 5   value      3178 non-null   float64
 6   unit       3178 non-null   object
dtypes: float64(1), object(6)
memory usage: 173.9+ KB

## air_quality, stations 데이터프레임 합치기(merge)

In [87]:
df = pd.merge(left=air_quality, right=stations_df)

In [88]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4182 entries, 0 to 4181
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   city                   4182 non-null   object
 1   country                4182 non-null   object
 2   date.utc               4182 non-null   object
 3   location               4182 non-null   object
 4   parameter              4182 non-null   object
 5   value                  4182 non-null   float64
 6   unit                   4182 non-null   object
 7   coordinates.latitude   4182 non-null   float64
 8   coordinates.longitude  4182 non-null   float64
dtypes: float64(3), object(6)
memory usage: 294.2+ KB

In [89]:
df.head(n=10)

,city,country,date.utc,location,parameter,value,unit,coordinates.latitude,coordinates.longitude
0,Paris,FR,2019-06-21 00:00:00+00:00,FR04014,no2,20.0,µg/m³,48.83724,2.3939
1,Paris,FR,2019-06-21 00:00:00+00:00,FR04014,no2,20.0,µg/m³,48.83722,2.3939
2,Paris,FR,2019-06-20 23:00:00+00:00,FR04014,no2,21.8,µg/m³,48.83724,2.3939
3,Paris,FR,2019-06-20 23:00:00+00:00,FR04014,no2,21.8,µg/m³,48.83722,2.3939
4,Paris,FR,2019-06-20 22:00:00+00:00,FR04014,no2,26.5,µg/m³,48.83724,2.3939
5,Paris,FR,2019-06-20 22:00:00+00:00,FR04014,no2,26.5,µg/m³,48.83722,2.3939
6,Paris,FR,2019-06-20 21:00:00+00:00,FR04014,no2,24.9,µg/m³,48.83724,2.3939
7,Paris,FR,2019-06-20 21:00:00+00:00,FR04014,no2,24.9,µg/m³,48.83722,2.3939
8,Paris,FR,2019-06-20 20:00:00+00:00,FR04014,no2,21.4,µg/m³,48.83724,2.3939
9,Paris,FR,2019-06-20 20:00:00+00:00,FR04014,no2,21.4,µg/m³,48.83722,2.3939

## stations 데이터프레임에서 중복되는 location 값 제거.

In [90]:
stations2_df = stations_df.drop_duplicates(subset='location')

In [91]:
stations2_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 58 entries, 0 to 65
Data columns (total 3 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   location               58 non-null     object
 1   coordinates.latitude   58 non-null     float64
 2   coordinates.longitude  58 non-null     float64
dtypes: float64(2), object(1)
memory usage: 1.8+ KB

## air_quaility와 stations2(중복 제거) 데이터프레임 합치기

In [92]:
df = pd.merge(left=air_quality, right=stations2_df)

In [93]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3178 entries, 0 to 3177
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   city                   3178 non-null   object
 1   country                3178 non-null   object
 2   date.utc               3178 non-null   object
 3   location               3178 non-null   object
 4   parameter              3178 non-null   object
 5   value                  3178 non-null   float64
 6   unit                   3178 non-null   object
 7   coordinates.latitude   3178 non-null   float64
 8   coordinates.longitude  3178 non-null   float64
dtypes: float64(3), object(6)
memory usage: 223.6+ KB

In [94]:
df.head(n=10)

,city,country,date.utc,location,parameter,value,unit,coordinates.latitude,coordinates.longitude
0,Paris,FR,2019-06-21 00:00:00+00:00,FR04014,no2,20.0,µg/m³,48.83724,2.3939
1,Paris,FR,2019-06-20 23:00:00+00:00,FR04014,no2,21.8,µg/m³,48.83724,2.3939
2,Paris,FR,2019-06-20 22:00:00+00:00,FR04014,no2,26.5,µg/m³,48.83724,2.3939
3,Paris,FR,2019-06-20 21:00:00+00:00,FR04014,no2,24.9,µg/m³,48.83724,2.3939
4,Paris,FR,2019-06-20 20:00:00+00:00,FR04014,no2,21.4,µg/m³,48.83724,2.3939
5,Paris,FR,2019-06-20 19:00:00+00:00,FR04014,no2,25.3,µg/m³,48.83724,2.3939
6,Paris,FR,2019-06-20 18:00:00+00:00,FR04014,no2,23.9,µg/m³,48.83724,2.3939
7,Paris,FR,2019-06-20 17:00:00+00:00,FR04014,no2,23.2,µg/m³,48.83724,2.3939
8,Paris,FR,2019-06-20 16:00:00+00:00,FR04014,no2,19.0,µg/m³,48.83724,2.3939
9,Paris,FR,2019-06-20 15:00:00+00:00,FR04014,no2,19.3,µg/m³,48.83724,2.3939