<a href="https://colab.research.google.com/github/JakeOh/202605_BD57/blob/main/lab_python/da10_merge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 데이터프레임 합치기

*   merge: 두 개 이상의 데이터프레임을 공통된 컬럼(들)을 기준으로 합치는 것. SQL의 join과 비슷.
*   concat: 두 개 이상의 데이터프레임을 축(axis)을 따라서 합치는 것.

# Imports

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# merge

In [2]:
emp = pd.DataFrame(data={
    'empno': [101, 102, 201, 202],
    'ename': ['Scott', 'Allen', 'King', '오쌤'],
    'deptno': [10, 20, 10, 40],
})

In [3]:
emp

   empno  ename  deptno
0    101  Scott      10
1    102  Allen      20
2    201   King      10
3    202     오쌤      40

In [4]:
dept = pd.DataFrame(data={
    'deptno': [10, 20, 30],
    'dname': ['IT', 'HR', 'Sales'],
})

In [5]:
dept

   deptno  dname
0      10     IT
1      20     HR
2      30  Sales

*   `pandas.merge(left, right, how, on, ...)` 함수
*   `pandas.DataFrame.merge(right, how, on, ...)` 메서드
*   파라미터 `how`: merge 방식(inner, left, right, outer). 기본값은 inner.
*   파라미터 `on`: merge(join) 기준이 되는 컬럼(들의 리스트). merge하는 컬럼 이름이 같은 경우에는 생략 가능.

## inner join

In [6]:
pd.merge(left=emp, right=dept)

   empno  ename  deptno dname
0    101  Scott      10    IT
1    102  Allen      20    HR
2    201   King      10    IT

In [7]:
emp.merge(right=dept)

   empno  ename  deptno dname
0    101  Scott      10    IT
1    102  Allen      20    HR
2    201   King      10    IT

## left outer join

In [8]:
pd.merge(left=emp, right=dept, how='left')

   empno  ename  deptno dname
0    101  Scott      10    IT
1    102  Allen      20    HR
2    201   King      10    IT
3    202     오쌤      40   NaN

In [9]:
emp.merge(right=dept, how='left')

   empno  ename  deptno dname
0    101  Scott      10    IT
1    102  Allen      20    HR
2    201   King      10    IT
3    202     오쌤      40   NaN

## right outer join

In [10]:
pd.merge(left=emp, right=dept, how='right')

   empno  ename  deptno  dname
0  101.0  Scott      10     IT
1  201.0   King      10     IT
2  102.0  Allen      20     HR
3    NaN    NaN      30  Sales

In [11]:
emp.merge(right=dept, how='right')

   empno  ename  deptno  dname
0  101.0  Scott      10     IT
1  201.0   King      10     IT
2  102.0  Allen      20     HR
3    NaN    NaN      30  Sales

## full outer join

In [12]:
pd.merge(left=emp, right=dept, how='outer')

   empno  ename  deptno  dname
0  101.0  Scott      10     IT
1  201.0   King      10     IT
2  102.0  Allen      20     HR
3    NaN    NaN      30  Sales
4  202.0     오쌤      40    NaN

In [13]:
emp.merge(right=dept, how='outer')

   empno  ename  deptno  dname
0  101.0  Scott      10     IT
1  201.0   King      10     IT
2  102.0  Allen      20     HR
3    NaN    NaN      30  Sales
4  202.0     오쌤      40    NaN

## merge 기준 컬럼 이름이 다른 경우

In [14]:
dept2 = pd.DataFrame(data={
    'dept_id': [10, 20, 30],
    'dept_name': ['아이티', '인사', '영업']
})

In [15]:
dept2

   dept_id dept_name
0       10       아이티
1       20        인사
2       30        영업

In [16]:
# inner join
emp.merge(right=dept2, left_on='deptno', right_on='dept_id')

   empno  ename  deptno  dept_id dept_name
0    101  Scott      10       10       아이티
1    102  Allen      20       20        인사
2    201   King      10       10       아이티

In [17]:
# left outer join
emp.merge(right=dept2, how='left', left_on='deptno', right_on='dept_id')

   empno  ename  deptno  dept_id dept_name
0    101  Scott      10     10.0       아이티
1    102  Allen      20     20.0        인사
2    201   King      10     10.0       아이티
3    202     오쌤      40      NaN       NaN

In [18]:
# right outer join
emp.merge(right=dept2, how='right', left_on='deptno', right_on='dept_id')

   empno  ename  deptno  dept_id dept_name
0  101.0  Scott    10.0       10       아이티
1  201.0   King    10.0       10       아이티
2  102.0  Allen    20.0       20        인사
3    NaN    NaN     NaN       30        영업

In [19]:
# full outer join
emp.merge(right=dept2, how='outer', left_on='deptno', right_on='dept_id')

   empno  ename  deptno  dept_id dept_name
0  101.0  Scott    10.0     10.0       아이티
1  201.0   King    10.0     10.0       아이티
2  102.0  Allen    20.0     20.0        인사
3    NaN    NaN     NaN     30.0        영업
4  202.0     오쌤    40.0      NaN       NaN