<a href="https://colab.research.google.com/github/JakeOh/202605_BD57/blob/main/lab_python/da11_index.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

# Series 인덱스

## 단일 계층 인덱스

In [2]:
s = pd.Series(data=np.random.rand(5), name='value')
#> Series 객체도 데이터프레임의 컬럼처럼 값들의 이름을 설정할 수 있음.

In [3]:
s

0    0.452451
1    0.761114
2    0.928600
3    0.238171
4    0.518821
Name: value, dtype: float64

In [4]:
s.index  #> Series의 index 속성 - RangeIndex

RangeIndex(start=0, stop=5, step=1)

In [5]:
s.values  #> Series의 values 속성 - 값들을 원소로 갖는 1차원 배열(numpy.ndarray)

array([0.45245075, 0.76111445, 0.92860006, 0.23817145, 0.51882115])

In [6]:
scores = pd.Series(data=np.random.randint(101, size=5),
                   index=['scott', 'tiger', 'king', 'allen', '홍길동'],
                   name='score')

In [7]:
scores

scott    76
tiger    77
king     80
allen    60
홍길동      46
Name: score, dtype: int64

In [8]:
scores.index  #> Index 객체

Index(['scott', 'tiger', 'king', 'allen', '홍길동'], dtype='object')

In [19]:
scores.index.nlevels

1

In [9]:
scores.values  #> ndarray 객체

array([76, 77, 80, 60, 46])

In [10]:
scores['scott']  # scores.loc['scott']

np.int64(76)

In [11]:
scores[['scott', '홍길동']]

scott    76
홍길동      46
Name: score, dtype: int64

## 계층적 인덱스(hierachical index, multi-level index)

In [14]:
scores2 = pd.Series(data=np.random.randint(101, size=6),
                    name='score',
                    index=[[1, 1, 1, 2, 2, 2], [1, 2, 3, 1, 2, 3]])
scores2

1  1     82
   2     97
   3     51
2  1    100
   2     24
   3     40
Name: score, dtype: int64

In [16]:
scores2.values

array([ 82,  97,  51, 100,  24,  40])

In [17]:
scores2.index  #> MultiIndex 객체

MultiIndex([(1, 1),
            (1, 2),
            (1, 3),
            (2, 1),
            (2, 2),
            (2, 3)],
           )

Multi-level index에서 indexing과 slicing

*   첫번째 계층(level)의 인덱스만 가지고 indexing과 slicing을 할 수 있음.
*   두번째 계층(level)의 인덱스만 가지고는 indexing과 slicing은 할 수 없음.
*   튜플 형태의 인덱스로는 indexing과 slicing을 할 수 있음.

In [18]:
scores2.index.nlevels

2

In [24]:
scores2.loc[1]  # scores[1]

1    82
2    97
3    51
Name: score, dtype: int64

In [25]:
scores2.loc[2]  # scores[2]

1    100
2     24
3     40
Name: score, dtype: int64

In [23]:
scores2.loc[1:2]

1  1     82
   2     97
   3     51
2  1    100
   2     24
   3     40
Name: score, dtype: int64

In [31]:
scores2[(1, 3)]  # indexing

np.int64(51)

In [32]:
scores2[[(1, 3), (2, 3)]]  # fancy indexing

1  3    51
2  3    40
Name: score, dtype: int64

In [34]:
scores2[(1, 2):(2, 2)]  # slicing

1  2     97
   3     51
2  1    100
   2     24
Name: score, dtype: int64

계층적 인덱스에서 인덱스의 순서 바꾸기

In [36]:
scores2.swaplevel()

1  1     82
2  1     97
3  1     51
1  2    100
2  2     24
3  2     40
Name: score, dtype: int64

In [37]:
# nlevels=3인 인덱스를 갖는 시리즈
np.random.seed(42)
s = pd.Series(data=np.random.rand(6),
              index=[np.arange(1, 7),
                     ['A'] * 3 + ['B'] * 3,
                     ['a', 'b', 'c'] * 2])
s

1  A  a    0.374540
2  A  b    0.950714
3  A  c    0.731994
4  B  a    0.598658
5  B  b    0.156019
6  B  c    0.155995
dtype: float64

In [41]:
s.loc[1:3]

1  A  a    0.374540
2  A  b    0.950714
3  A  c    0.731994
dtype: float64

In [42]:
s.swaplevel()
# 파라미터 i=-2, j=-1 기본값. 끝에서 두번째 인덱스와 마지막 인덱스를 서로 바꿈(swap).

1  a  A    0.374540
2  b  A    0.950714
3  c  A    0.731994
4  a  B    0.598658
5  b  B    0.156019
6  c  B    0.155995
dtype: float64

In [44]:
s.swaplevel(i=1, j=2)

1  a  A    0.374540
2  b  A    0.950714
3  c  A    0.731994
4  a  B    0.598658
5  b  B    0.156019
6  c  B    0.155995
dtype: float64

In [48]:
s.swaplevel(i=0, j=1)  # 첫번째 인덱스와 두번째 인덱스를 서로 바꿈(swap).

A  1  a    0.374540
   2  b    0.950714
   3  c    0.731994
B  4  a    0.598658
   5  b    0.156019
   6  c    0.155995
dtype: float64